COUNT_FUNCTION = "count"
AVG_FUNCTION = "avg"
MAX_FUNCTION = "max"
MIN_FUNCTION = "min"
SUM_FUNCTION = "sum"

VARIABLE = "variable"
TABLE = "table"
FUNCTIONS = "functions"
REQUIRED_FUNCTIONS = "required_functions"

ERROR = "error"

FUNCTION_MAPPING = {
    COUNT_FUNCTION: [COUNT_FUNCTION],
    AVG_FUNCTION: [SUM_FUNCTION, COUNT_FUNCTION],
    MAX_FUNCTION: [MAX_FUNCTION],
    MIN_FUNCTION: [MIN_FUNCTION],
    SUM_FUNCTION: [SUM_FUNCTION]
}
